[workspace.package]
authors = ["Horizen Labs <admin@horizenlabs.io>"]
edition = "2021"
repository = "TODO"
license = "GPL-3.0-only"

[workspace]
resolver = "2"

members = [
    "pack1",
    "pack2",
]

[workspace.dependencies]
