name: CI-build-only
run-name: Workflow performing only build
on:
  push:
    branches-ignore:
      - main
env:
  RUST_BACKTRACE: 1
jobs:
  build-only:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    outputs:
      abort: ${{ steps.branchCheck.outputs.abort }}
    runs-on: ${{ matrix.os }}
    steps:
    # - name: Set environment variable
    #   run: echo "MY_VAR=my_value" >> $GITHUB_ENV
    # - name: Echo environment variable
    #   run: echo $MY_VAR
      - name: Check not a PR
        run: |
          $outstandingPrBranches = & gh pr list --json headRefName --repo $env:repository | ConvertFrom-Json
          $triggeringBranch = $env:triggeringBranch 
          if (($outstandingPrBranches | ?{ "refs/heads/$($_.headRefName)" -eq "$triggeringBranch" }).count -gt 0)
          {
            echo "abort=true" >> $GITHUB_ENV
          }
        env:
          repository: ${{ github.repository }}
          triggeringBranch: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
      - name: Echo environment variable
        run: echo $abort
        env:
          repository: ${{ github.repository }}
          triggeringBranch: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
      #   env:
      #     repository: ${{ github.repository }}
      #     triggeringBranch: ${{ github.ref }}
      #     GH_TOKEN: ${{ github.token }}
      #   shell: pwsh
      #   id: branchCheck
      # - name: Checkout branch
      #   if: env.abort == 'true'
      #   uses: actions/checkout@v4
      # - name: Checkout branch
      #   if: env.abort == 'true'
      #   run: cargo build --all-features