name: CI-build-only
run-name: Workflow performing only build
on:
  push:
    branches-ignore:
      - main
env:
  RUST_BACKTRACE: 1
jobs:
  build-only:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set environment variable
      run: |
        $version = "1.0.0" # Replace this with your logic to get the version
        echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    - name: Echo environment variable
      run: echo "Version is $Env:VERSION"
      shell: pwsh













    # # - name: Set environment variable
    # #   run: echo "MY_VAR=my_value" >> $GITHUB_ENV
    # # - name: Echo environment variable
    # #   run: echo $MY_VAR
    #   - name: Check not a PR
    #     run: |
    #       pr_branches=$(gh pr list --json headRefName --repo $GITHUB_REPOSITORY)
    #       if [[ $(echo "$pr_branches" | jq -r --arg GITHUB_REF '.[].headRefName | select(. == $GITHUB_REF)') ]]; then
    #         echo "This push is associated with a pull request. Skipping the job."
    #         echo "abort=true" >> "$GITHUB_OUTPUT"
    #       fi
    #     env:
    #       GH_TOKEN: ${{ github.token }}
    #   - name: Echo environment variable
    #     run: echo $abort
    #     env:
    #       GH_TOKEN: ${{ github.token }}
    #   #   env:
    #   #     repository: ${{ github.repository }}
    #   #     triggeringBranch: ${{ github.ref }}
    #   #     GH_TOKEN: ${{ github.token }}
    #   #   shell: pwsh
    #   #   id: branchCheck
    #   # - name: Checkout branch
    #   #   if: env.abort == 'true'
    #   #   uses: actions/checkout@v4
    #   # - name: Checkout branch
    #   #   if: env.abort == 'true'
    #   #   run: cargo build --all-features