name: CI-build-only
run-name: Workflow performing only build
on:
  push:
    branches-ignore:
      - main
env:
  RUST_BACKTRACE: 1
jobs:
  build-only:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    outputs:
      abort: ${{ steps.branchCheck.outputs.abort }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check not a PR
        run: |
          $listOfPrBranches = & gh pr list --json headRefName --repo $env:repository | ConvertFrom-Json
          $triggeringBranch = $env:triggeringBranch 
          if (($listOfPrBranches | ?{ "refs/heads/$($_.headRefName)" -eq "$triggeringBranch" }).count -gt 0)
          {
            "abort=true" >> $GITHUB_ENV
          }
          echo "value ${{ env.Failures }}"
        env:
          repository: ${{ github.repository }}
          triggeringBranch: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        id: branchCheck
      - name: Checkout branch
        if: env.abort
        uses: actions/checkout@v4
      - name: Checkout branch
        if: env.abort
        uses: actions/checkout@v4