name: CI-build-only
run-name: Workflow performing only build
on:
  push:
    branches-ignore:
      - main
env:
  RUST_BACKTRACE: 1
jobs:
  check-not-PR:
    outputs:
      abort: ${{ steps.branchCheck.outputs.abort }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo HitPoint1
          $listOfPrBranches = & gh pr list --json headRefName --repo $env:repository | ConvertFrom-Json
          echo HitPoint2
        env:
          repository: ${{ github.repository }}
          triggeringBranch: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        id: branchCheck
  build-only:
    needs: check-not-PR
    if: ${{ needs.check-not-PR.outputs.abort != 'true' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Build (debug)
        run: cargo build --all-features