name: CI-build&test&lint&coverage

run-name: Workflow performing all CI steps (build, unit tests, integration tests, linting, coverage)

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  check-cargo-build:
    if: success() || failure()
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        if: success() || failure()
        uses: actions/checkout@v4
      - name: Build (release)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cargo build --release --all-features
      - name: Build (debug)
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        run: cargo build --all-features
      - name: Unit tests
        if: success() || failure()
        run: cargo test --lib --bins --no-fail-fast
      - name: Integration tests
        if: success() || failure()
        run: cargo test --test '*' --no-fail-fast
      - name: Linting
        if: success() || failure()
        run: cargo clippy
      - name: Coverage
        if: success() || failure()
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '--ignore-tests --out Lcov'
        # run: cargo tarpaulin --ignore-tests --out Lcov
        