name: CI-check
run-name: "Workflow performing CI check"

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]*
    branches:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Check
        run: |
          echo "Tag name from GITHUB_REF: $GITHUB_REF"
          echo "Tag name from github.ref: ${{ github.ref }}"
          echo "Tag name from github.ref: ${{ github.ref_name }}"
          TAG_NAME="${{ github.ref_name }}"
          DOCKER_TAG_NAME="${TAG_NAME:1}"
          echo "${TAG_NAME}"-"${DOCKER_TAG_NAME}"
          if [[ "${TAG_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo if-branch
          else
            echo else-branch
          fi