name: CI-integration-tests-and-lint

run-name: $CI integration testing and linting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  RUST_BACKTRACE: 1

jobs:
  check-cargo-test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test '*'' --no-fail-fast # for running integration tests
  check-cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy