name: CI-PR
run-name: ${{ github.actor }} is learning GitHub Actions (CI-PR)
on:
  pull_request:
    # types: [opened, synchronize]
    # branches:
    #   - main
jobs:
  check-cargo-test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --tests --no-fail-fast # for running all tests