name: CI-temp
run-name: "Workflow performing CI check"

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]*'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Print wksp
        run: echo ${GITHUB_WORKSPACE}
      - name: Print dirs
        run: ls -R
      # - name: Script
      #   run: |
      #     #!/bin/bash
      #     set -eEuo pipefail

      #     # Initialize counters for unit tests
      #     unit_total_passed=1
      #     unit_total_failed=2
      #     unit_total_runtime=3.4

      #     passed_formatted="*Passed*: ${unit_total_passed}"
      #     failed_formatted="*Failed*: ${unit_total_failed}"
      #     runtime_formatted="*Runtime*: ${unit_total_runtime}s"
      #     echo N0-B
      #     echo "E2E_TEST_SUMMARY=*E2E Tests*\n${passed_formatted}, ${failed_formatted}, ${runtime_formatted}" >> $GITHUB_ENV
      #     echo N0-A
      - name: Summarize Test Data
        run: ${GITHUB_WORKSPACE}/.github/scripts/summarize_tests.sh
